
#
# IPO Summary:
#
# INPUT: 
# client_first_name
# client_last_name
# client_email
# member_id - login username, a string or memberpress account number [rename to 'username']
# subscription_id - memberpress subscription number (mp-sub-5fa2a2ac5fa12 or 'byo')
# plan_title - size of server
#
# PROCESSING: Creates AWX Account for user, append random string to 'byo', creates initial organisation.yml and server_vars.yml file. Also creates initial '{{ subscription_id }} Provision Server' playbook in users account.
#
# OUTPUT: Working AWX account at provision stage.
#
# Relies on the following file on the AWX host: /var/lib/awx/hosting/hosting_vars.yml
# do_api_token: value
# do_spaces_access_key: value
# do_spaces_secret_key: value
# do_image_master: debian-10-x64
# tower_host: value
# tower_username: value
# tower_password: value

- name: "Spawn/recreate an Organisation and add Provision script to it."
  hosts: "dummyvalue.com"
#  become: true
  gather_facts: false

  roles:
    - create-awx-account
